[[redirects]]
from = "/blog/*"
to = "/blog-post.html"
status = 200

[[redirects]]
from = "/blog"
to = "/blogs.html"
status = 301
force = true

[[redirects]]
from = "/jobs/*"
to = "/job-detail.html"
status = 200